openapi: 3.2.0
info:
  title: Merchant API HPP Webhook Prepare success API
  version: 3.0.0
  description: Merchant API HPP Webhook
servers:
- url: http://127.0.0.1:10010/v3
security:
- accountId: []
  accountPassword: []
tags:
- name: Prepare success
paths:
  /registered-prepare-address:
    post:
      tags:
      - Prepare success
      summary: ''
      operationId: postprepare
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prepare'
      responses:
        '200':
          description: 'Expected response: HTTP status code 200'
components:
  schemas:
    PrepareWebhook:
      type: object
      properties:
        id:
          description: Unique webhook ID
          type: string
          example: '5455223499197002'
          maxLength: 16
          minLength: 16
        type:
          description: '[Webhook Type] hosted_payment_prepare'
          type: string
          example: hosted_payment_prepare
          maxLength: 50
          minLength: 1
      required:
      - id
      - type
    Prepare:
      title: prepare
      properties:
        webhook:
          $ref: '#/components/schemas/PrepareWebhook'
        requestId:
          description: Unique request ID received after a successful initial request for the appropriate action
          type: string
          example: bdc84215-d2ed-4e39-b4dd-e7b3ba85e38b
          maxLength: 36
          minLength: 36
        redirectUrl:
          description: URL with redirect link
          type: string
          example: https://example-url.gateway.com/2a731e2ddfebc14ca4834e44851fda59
          maxLength: 255
          minLength: 1
      type: object
      required:
      - requestId
      - redirectUrl
  securitySchemes:
    accountId:
      type: apiKey
      in: header
      name: x-auth-account-id
    accountPassword:
      type: apiKey
      in: header
      name: x-auth-account-password
