openapi: 3.2.0
info:
  title: Tribe Payments Health Check API
  description: ''
  version: 0.0.0
servers:
- url: /
  description: ''
security:
- Bearer: []
- Token: []
tags:
- name: Health Check
paths:
  /v1/health-check:
    parameters: []
    post:
      operationId: postHealthCheckCollection
      tags:
      - Health Check
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              example: ok
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/BadRequestErrorResponseDto'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedErrorResponseDto'
        '415':
          description: Unsupported media type
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnsupportedMediaTypeErrorResponseDto'
        '500':
          description: Internal server error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponseDto'
      summary: Performs system health check
      description: Checks the status of the system and network connection as well as validates the received credentials.
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
            example:
              anyKey: anyValue
        required: false
      deprecated: false
components:
  schemas:
    InternalServerErrorResponseDto:
      type: object
      properties:
        type:
          type: string
          description: URI reference that identifies the problem type. If not specified, the default value is 'about:blank'.
          example: https://tools.ietf.org/html/rfc2616#section-10
        title:
          type: string
          description: Short human-readable summary of the problem type.
          example: An error occurred
        detail:
          type: string
          description: Human-readable explanation of the specific problem that occurred.
          example: Internal Server Error
      required:
      - type
      - title
      - detail
    UnauthorizedErrorResponseDto:
      type: object
      properties:
        type:
          type: string
          description: URI reference that identifies the problem type. If not specified, the default value is 'about:blank'.
          example: https://tools.ietf.org/html/rfc2616#section-10
        title:
          type: string
          description: Short human-readable summary of the problem type.
          example: An error occurred
        detail:
          type: string
          description: Human-readable explanation of the specific problem that occurred.
          example: Full authentication is required to access this resource.
      required:
      - type
      - title
      - detail
    BadRequestErrorResponseDto:
      type: object
      properties:
        type:
          type: string
          description: URI reference that identifies the problem type. If not specified, the default value is 'about:blank'.
          example: https://tools.ietf.org/html/rfc2616#section-10
        title:
          type: string
          description: Short human-readable summary of the problem type.
          example: An error occurred
        detail:
          type: string
          description: Human-readable explanation of the specific problem that occurred.
          example: Syntax error
      required:
      - type
      - title
      - detail
    UnsupportedMediaTypeErrorResponseDto:
      type: object
      properties:
        type:
          type: string
          description: URI reference that identifies the problem type. If not specified, the default value is 'about:blank'.
          example: https://tools.ietf.org/html/rfc2616#section-10
        title:
          type: string
          description: Short human-readable summary of the problem type.
          example: An error occurred
        detail:
          type: string
          description: Human-readable explanation of the specific problem that occurred.
          example: The content-type "text/plain" is not supported. Supported MIME types are "application/json".
      required:
      - type
      - title
      - detail
  securitySchemes:
    Bearer:
      type: apiKey
      description: Value for the bearer header parameter.
      name: bearer
      in: header
    Token:
      type: apiKey
      description: Value for the X-AUTH-TOKEN header parameter.
      name: X-AUTH-TOKEN
      in: header
